### ISSUE TITLE
Error in der_strict_encode_sig()

### ISSUE THREAD

**Issue by michailbrynard** [blockcypher/blockcypher-python#16]
When running make_tx_signatures(), the der_strict_encode_sig() function throws an error when executing line 13:
TypeError: ord() expected string of length 1, but int found

I fixed this by replacing der_strict_encode_sig() with der_encode_sig() from https://github.com/vbuterin/pybitcointools (currently version bitcoin==1.1.38) which is now BIP66 compliant.

**Comment by mflaxman** [comment]
Thanks for the report and suggested fix @michailbrynard !

pybitcointools is unfortunately [not that well maintained](https://github.com/vbuterin/pybitcointools/pulls) so at one point I had to use my own der encoding because pybitcointools wasn't bip66 complaint. I'm glad to hear they've upgraded, I'll follow your suggestion and update this library to use their (probably better version) of DER encoding once I test it. PR welcome of course :)

How are you finding TX signing with this library? It's inherently a very complicated process, I'm hoping this library makes it simpler.

**Comment by mflaxman** [comment]
Fixed by @michailbrynard in https://github.com/blockcypher/blockcypher-python/pull/17, thanks!

Will bump version number and push a new version to pypi.

**Comment by michailbrynard** [comment]
Thanks for the quick feedback @mflaxman . 

I like the simplicity of relying on the Blockcypher API to construct transactions. The included simple transaction function is a great help for getting up and running quickly.
