### ISSUE TITLE
simple_spend_tx accepting privkey_wif

### ISSUE THREAD

**Issue by hrhristov** [blockcypher/blockcypher-python#20]
I noticed that simple_spend_tx accepts from_privkey_hex in wif format, not only hex.

Is it ok to depend on this? If yes, maybe the param can be renamed accordingly?

**Comment by mflaxman** [comment]
Hey @hrhristov, thanks for trying that and good find!

This library uses pybitcointools for ECDSA operations and I just went through and traced their code and it turns out they accept the private key in many formats:
https://github.com/vbuterin/pybitcointools/blob/34675ab3ee40e1baebb169f46df74d46849560bf/bitcoin/main.py#L236-L246

So I don't want to say with 100% certainty because I'd need to first test it across several different coins (testnet, doge, litecoin, etc), but I think that would work.

Has it been working for you?

I was previously relying on [bitmerchant](https://github.com/sbuss/bitmerchant) for conversion from WIF to hex across different altcoins, but what you've found is a much better solution.

**Comment by hrhristov** [comment]
Yes, I can confirm it is working with WIF format for BTC, LTC, DOGE

**Comment by wizardofozzie** [comment]
For *pybitcointools* WIFs will always work as a private key, and IMO are the preferred private key format.

However is one were to use hex, it is important to note that compressed private keys have `01` appended to the 64 bytes of hex data.

**Comment by mflaxman** [comment]
This is now fixed in #22, thanks @hrhristov and @wizardofozzie!

Note that it's now `simple_spend` and not `simple_spend_tx` since I didn't want to maintain backwards compatibility (`from_privkey_hex` is now `from_privkey`)... Does this look good?

PRs are always very welcome, keep them coming :)

**Comment by hrhristov** [comment]
Perfect, thanks! I have just tested it, works like expected.
