### ISSUE TITLE
get_forwarding_address returns only the address.

### ISSUE THREAD

**Issue by Dirbaio** [blockcypher/blockcypher-python#6]
get_forwarding_address returns only the address, but in many cases you also need the ID, for deleting it later. I think the function should return the whole response dictionary.

https://github.com/blockcypher/blockcypher-python/blob/master/blockcypher/api.py#L570

Thanks :)

**Comment by mflaxman** [comment]
Thanks for the feedback Dario!

That's a good point, I'll add support for it (you're welcome to submit a PR
if you like of course).

I think maybe a new method called get_forwarding_address_details() would be
the best solution since:
1) I don't want to change what this function does for existing users
2) I'm guessing most people don't actually want to store that info and will
just use the existing minimal function. Remember that you can always look
it up later by API call.

Does that make sense?

On Thursday, February 5, 2015, Dario Nieuwenhuis <notifications@github.com>
wrote:

> get_forwarding_address returns only the address, but in many cases you
> also need the ID, for deleting it later. I think the function should return
> the whole response dictionary.
>
>
> https://github.com/blockcypher/blockcypher-python/blob/master/blockcypher/api.py#L570
>
> Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blockcypher/blockcypher-python/issues/6>.
>


-- 
Sent from my iPhone

**Comment by Dirbaio** [comment]
Sounds better, yes. You have a good point about not breaking existing functionality.

I'll send a PR right now.

**Comment by mflaxman** [comment]
Fixed nicely in c6cc50e22f1ea6c595751f0e3976edaa99734c62
